version: '3.9'

x-service-defaults: &service-defaults
  networks:
    - 'default'

services:
  web:
    <<: *service-defaults
    profiles: [backend]
    ports:
      - "80:80"
      - "443:443"
    build: .
    volumes:
      - ".:/app"
    environment:
      WEB_ALIAS_DOMAIN: "${APP_HOST}"
      WEB_DOCUMENT_ROOT: "/app/public"

  mysql:
    <<: *service-defaults
    profiles: [backend]
    hostname: "${MYSQL_HOST}"
    ports:
      - "3306:3306"
      - "33060:33060"
    image: "mysql/mysql-server:8.0.25"
    #command: "--default-authentication-plugin=mysql_native_password --sql_mode='NO_ENGINE_SUBSTITUTION'"
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

volumes:
  mysql_data:
    driver: "local"
